packages:
  - 'packages/*'
  - 'apps/*'
  - 'docs/*'

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@swc/core': false
  esbuild: false
  lefthook: true
  less: false
  nx: true
  prisma: false
  sharp: false
  unrs-resolver: false

overrides:
  '@nx/devkit': '23.1.1'
  'nx': '23.1.1'

catalog:
  '@tailwindcss/postcss': '4.3.3'
  '@takumi-rs/image-response': '0.73.1'
  'fumadocs-core': '16.10.5'
  'fumadocs-docgen': '3.0.10'
  'fumadocs-mdx': '14.3.2'
  'fumadocs-typescript': '5.2.6'
  'fumadocs-ui': '16.10.5'
  'lucide-react': '0.577.0'
  'next': '16.2.11'
  'react-dom': '19.2.8'
  'react': '19.2.8'
  'tailwind-merge': '3.6.0'
  'tailwindcss': '4.3.1'
  'tslib': '2.8.1'
  'tsx': '4.23.1'
